# Generated by Django 3.2.21 on 2023-09-29 17:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20230930_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 29, 17, 1, 21, 931272, tzinfo=utc)),
        ),
    ]
